before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh
dist: trusty
language: bash
sudo: required
notifications:
  slack:
    rooms:
      secure: Oay3qywZ2wDkyR4/BIOWKnL2uaFqy4TnLre7Io+5xW32bA0Kkbd6ALb1ZbX1CLxs8RpqDu3BhS27zQLueYrTKgiKdYRvYjWN5C0esezY5NlVLtlpFHQIfn2nw0pRxrveI4SbAaaSnVLigBljesGQf8G5nzjCwO1lowuPskDxvODbsXrg39dHo5WcF6oQi6eWI3p4BsX74qmcBJZWnGxMoEEv4DaZU6VX8DabAYCBNVT6uRydOmXRc7RuvoSM+sDtK0zCBuQs5TwlbtwVRqHTguUvHiLm5jPtorLlapBn6cVb9tcEBnoJ5A47NL22YjvGRvr2urwWLRnSZyF7ncDBKHsAJ0UHQnoObKQ3MaGoctKqd/Ig7Is618BZc3n65zz9lbBLAio/EgwYc8jZJZVjFXHpvOoQPIndqZz0XcY1k+PFzXiKS4k3rmtLG4VY4nQe4aFbOZN+82ek+4zOtxxkKKRRYRCwt5myt/ZYAtoXiNBNq582qfQb1lQTlVTYZROBgZAYlIVCuWFg3bP+TUKLkRxgrxSHZ5RN0ftHaKUEP7AbSABcKWMbHz3RFgqXtKoPWJeXnjNYTKUcwqvqUUI25CUL4VHxus8TCQXVlMP6Bf75r9t4tq/uBpmFjyinS5ivrS1c/zs+Qp+aaCxef/pDXyKUbjCkziF/B5K+keuG84o=
