#cloud-config
disable_root: true
repo_update: true
repo_upgrade: true
apt:
  preserve_source_list: true
users:
  - name: appuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNanYKaVkoEzb8fzd/+fnOu4f11AymMzHyX6WrZ0yA/7oyXwbFTNCEGGiq16ALAWAXjBAPTrlwG7UUFZnh8t+693GW6/jLjXGmDvGdkFCqos9S/usXWAUL5xUQGSCJm5unHQ8vT0PfBHQ5KfwmLY5s3cTVf5LnKp2wFm4jEqWAK8THwE6ZTg8C4kvbkZvesAP5RzGiqLAvltp7nKEWreLFEM3oCnxIAbaeSLD3MCVQSJ6VxpNy4N93a+STpCSrPDlDmLT9ITNLhYj/razF2k1GzNuNFjLuQ7tel69ZZCxtgU5QY0js7tIXVUNi4qDDLIfey+XGh9EkBVw1H/e0Awoh appuser"
runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - sudo apt --assume-yes install git
  - sudo apt-get --assume-yes install mongodb-org
  - sudo apt --assume-yes install ruby-full ruby-bundler build-essential
  - sudo systemctl start mongod
  - sudo systemctl enable mongod
  - cd ~
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit && bundle install
  - puma -d
